# Generated by Django 5.2.4 on 2025-09-10 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryChina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(help_text='Nom du produit ou article', max_length=200)),
                ('code_produit', models.CharField(help_text='Code unique du produit', max_length=50, unique=True)),
                ('categorie', models.CharField(choices=[('electronique', 'Électronique'), ('vetements', 'Vêtements'), ('maison', 'Maison & Jardin'), ('automobile', 'Automobile'), ('beaute', 'Beauté & Santé'), ('sport', 'Sport & Loisirs'), ('outils', 'Outils & Industrie'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('fournisseur_nom', models.CharField(help_text='Nom du fournisseur chinois', max_length=200)),
                ('fournisseur_contact', models.CharField(blank=True, help_text='Contact du fournisseur (WeChat, Téléphone)', max_length=100)),
                ('prix_unitaire_yuan', models.DecimalField(decimal_places=2, help_text="Prix d'achat en Yuan chinois", max_digits=10)),
                ('prix_unitaire_fcfa', models.DecimalField(blank=True, decimal_places=2, help_text='Prix équivalent en FCFA (calculé automatiquement)', max_digits=10, null=True)),
                ('taux_change_utilise', models.DecimalField(blank=True, decimal_places=4, help_text='Taux de change Yuan/FCFA utilisé', max_digits=8, null=True)),
                ('quantite_stock', models.PositiveIntegerField(default=0, help_text='Quantité en stock')),
                ('quantite_minimale', models.PositiveIntegerField(default=10, help_text="Seuil d'alerte stock minimum")),
                ('poids_unitaire', models.DecimalField(blank=True, decimal_places=3, help_text='Poids unitaire en kg', max_digits=8, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('rupture', 'En rupture'), ('commande', 'En commande'), ('discontinu', 'Discontinué')], default='actif', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du produit')),
                ('image_produit', models.ImageField(blank=True, help_text='Photo du produit', null=True, upload_to='inventory_china/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('admin_createur', models.ForeignKey(limit_choices_to={'is_admin_chine': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire Chine',
                'verbose_name_plural': 'Inventaires Chine',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='OperationChina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operation', models.CharField(editable=False, help_text='Numéro auto-généré: OP + date + compteur', max_length=20, unique=True)),
                ('type_operation', models.CharField(choices=[('achat', 'Achat produit'), ('vente', 'Vente produit'), ('entree_stock', 'Entrée en stock'), ('sortie_stock', 'Sortie de stock'), ('expedition', 'Expédition vers Mali'), ('retour', 'Retour/Échange'), ('inventaire', 'Correction inventaire')], max_length=20)),
                ('quantite', models.PositiveIntegerField(help_text="Quantité concernée par l'opération")),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, help_text="Prix unitaire de l'opération", max_digits=10, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, help_text="Montant total de l'opération", max_digits=12, null=True)),
                ('monnaie', models.CharField(choices=[('CNY', 'Yuan Chinois'), ('USD', 'Dollar US'), ('XOF', 'FCFA')], default='CNY', max_length=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('description', models.TextField(help_text="Description de l'opération")),
                ('fournisseur_contact', models.CharField(blank=True, help_text='Contact du fournisseur/client', max_length=200)),
                ('reference_externe', models.CharField(blank=True, help_text='Référence externe (bon de commande, facture, etc.)', max_length=100)),
                ('date_operation', models.DateTimeField(help_text="Date effective de l'opération")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('admin_responsable', models.ForeignKey(limit_choices_to={'is_admin_chine': True}, on_delete=django.db.models.deletion.CASCADE, related_name='operations_gerees', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='admin_chine_app.inventorychina')),
            ],
            options={
                'verbose_name': 'Opération Chine',
                'verbose_name_plural': 'Opérations Chine',
                'ordering': ['-date_operation'],
            },
        ),
    ]
