# Generated by Django 5.2.4 on 2025-09-11 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_chine_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationchina',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='operationchina',
            name='admin_responsable',
        ),
        migrations.CreateModel(
            name='TransfertArgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transfert', models.CharField(help_text='Numéro unique du transfert', max_length=20, unique=True)),
                ('montant_fcfa', models.DecimalField(decimal_places=2, help_text='Montant en FCFA', max_digits=15)),
                ('montant_yuan', models.DecimalField(blank=True, decimal_places=2, help_text='Montant équivalent en Yuan chinois', max_digits=15, null=True)),
                ('taux_change', models.DecimalField(blank=True, decimal_places=6, help_text='Taux de change FCFA/Yuan utilisé', max_digits=10, null=True)),
                ('methode_transfert', models.CharField(choices=[('virement_bancaire', 'Virement bancaire'), ('western_union', 'Western Union'), ('moneygram', 'MoneyGram'), ('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('autre', 'Autre')], help_text='Méthode utilisée pour le transfert', max_length=30)),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('envoye', 'Envoyé'), ('confirme_chine', 'Confirmé en Chine'), ('annule', 'Annulé')], default='initie', max_length=20)),
                ('date_initiation', models.DateTimeField(auto_now_add=True, help_text="Date d'initiation du transfert")),
                ('date_envoi', models.DateTimeField(blank=True, help_text="Date effective d'envoi", null=True)),
                ('date_confirmation', models.DateTimeField(blank=True, help_text='Date de confirmation de réception en Chine', null=True)),
                ('reference_externe', models.CharField(blank=True, help_text='Référence du service de transfert (Western Union, etc.)', max_length=100)),
                ('destinataire_nom', models.CharField(help_text='Nom du destinataire en Chine', max_length=200)),
                ('destinataire_telephone', models.CharField(help_text='Téléphone du destinataire en Chine', max_length=20)),
                ('destinataire_adresse', models.TextField(help_text='Adresse du destinataire en Chine')),
                ('motif_transfert', models.TextField(help_text="Motif du transfert d'argent")),
                ('frais_transfert', models.DecimalField(decimal_places=2, default=0, help_text='Frais de transfert en FCFA', max_digits=10)),
                ('justificatifs', models.JSONField(blank=True, default=list, help_text='Liste des documents justificatifs')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur le transfert')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('admin_chine_confirmateur', models.ForeignKey(blank=True, help_text='Administrateur Chine qui a confirmé la réception', limit_choices_to={'is_admin_chine': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_chine_confirmes', to=settings.AUTH_USER_MODEL)),
                ('admin_chine_initiateur', models.ForeignKey(help_text='Administrateur Chine qui a initié le transfert', limit_choices_to={'is_admin_chine': True}, on_delete=django.db.models.deletion.CASCADE, related_name='transferts_chine_inities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Transfert d'Argent",
                'verbose_name_plural': "Transferts d'Argent",
                'ordering': ['-date_initiation'],
            },
        ),
        migrations.DeleteModel(
            name='InventoryChina',
        ),
        migrations.DeleteModel(
            name='OperationChina',
        ),
    ]
