# Generated by Django 5.2.4 on 2025-09-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_chine_app', '0002_remove_operationchina_produit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransfertArgent',
        ),
    ]
