# Generated by Django 5.2.4 on 2025-07-22 00:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportOperationnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du rapport', max_length=200)),
                ('type_rapport', models.CharField(choices=[('journalier', 'Rapport Journalier'), ('hebdomadaire', 'Rapport Hebdomadaire'), ('mensuel', 'Rapport Mensuel'), ('financier', 'Rapport Financier'), ('synthese', 'Rapport de Synthèse')], max_length=20)),
                ('periode_debut', models.DateField(help_text='Début de la période couverte')),
                ('periode_fin', models.DateField(help_text='Fin de la période couverte')),
                ('contenu_json', models.JSONField(help_text='Contenu du rapport au format JSON')),
                ('fichier_pdf', models.FileField(blank=True, help_text='Fichier PDF du rapport', null=True, upload_to='rapports/')),
                ('envoye_admins', models.BooleanField(default=False, help_text='Rapport envoyé aux administrateurs')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport Opérationnel',
                'verbose_name_plural': 'Rapports Opérationnels',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tarif', models.CharField(help_text='Nom du tarif (ex: Tarif Standard, Tarif Express, etc.)', max_length=100)),
                ('methode_calcul', models.CharField(choices=[('par_kilo', 'Par Kilo'), ('par_metre_cube', 'Par Mètre Cube')], help_text='Méthode de calcul du prix', max_length=20)),
                ('prix_par_kilo', models.DecimalField(blank=True, decimal_places=2, help_text='Prix en FCFA par kilogramme', max_digits=8, null=True)),
                ('prix_par_m3', models.DecimalField(blank=True, decimal_places=2, help_text='Prix en FCFA par mètre cube', max_digits=10, null=True)),
                ('prix_forfaitaire', models.DecimalField(blank=True, decimal_places=2, help_text='Prix forfaitaire en FCFA', max_digits=10, null=True)),
                ('poids_minimum', models.DecimalField(decimal_places=2, default=0, help_text='Poids minimum pour appliquer ce tarif (en kg)', max_digits=8)),
                ('poids_maximum', models.DecimalField(blank=True, decimal_places=2, help_text='Poids maximum pour ce tarif (en kg, null = illimité)', max_digits=8, null=True)),
                ('volume_minimum', models.DecimalField(decimal_places=6, default=0, help_text='Volume minimum pour ce tarif (en m3)', max_digits=8)),
                ('volume_maximum', models.DecimalField(blank=True, decimal_places=6, help_text='Volume maximum pour ce tarif (en m3, null = illimité)', max_digits=8, null=True)),
                ('actif', models.BooleanField(default=True, help_text='Tarif actif ou non')),
                ('date_debut', models.DateField(default=django.utils.timezone.now, help_text='Date de début de validité du tarif')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de validité (null = illimitée)', null=True)),
                ('pays_destination', models.CharField(choices=[('ML', 'Mali'), ('SN', 'Sénégal'), ('CI', "Côte d'Ivoire"), ('BF', 'Burkina Faso'), ('NE', 'Niger'), ('GN', 'Guinée'), ('MR', 'Mauritanie'), ('GM', 'Gambie'), ('GW', 'Guinée-Bissau'), ('ALL', 'Tous les pays')], default='ML', help_text='Pays de destination pour ce tarif', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du tarif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifs_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarif de Transport',
                'verbose_name_plural': 'Tarifs de Transport',
                'ordering': ['-date_creation'],
            },
        ),
    ]
