# Generated by Django 5.2.4 on 2025-09-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingprice',
            name='methode_calcul',
            field=models.CharField(choices=[('par_kilo', 'Par Kilo'), ('par_metre_cube', 'Par Mètre Cube'), ('forfaitaire', 'Prix Forfaitaire'), ('mixte', 'Mixte (Poids + Volume)')], help_text='Méthode de calcul du prix', max_length=20),
        ),
    ]
