# Generated by Django 5.2.4 on 2025-11-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0002_alter_shippingprice_methode_calcul'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingprice',
            name='prix_par_piece',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix en FCFA par pièce (pour téléphones, électronique, etc.)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='type_colis',
            field=models.CharField(choices=[('standard', 'Standard'), ('telephone', 'Téléphone'), ('electronique', 'Électronique'), ('all', 'Tous types')], default='all', help_text='Type de colis concerné (pour tarif à la pièce)', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='type_transport',
            field=models.CharField(choices=[('cargo', 'Cargo'), ('express', 'Express'), ('bateau', 'Bateau'), ('all', 'Tous')], default='all', help_text='Type de transport concerné par ce tarif', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='methode_calcul',
            field=models.CharField(choices=[('par_kilo', 'Par Kilo'), ('par_metre_cube', 'Par Mètre Cube'), ('par_piece', 'Par Pièce'), ('forfaitaire', 'Prix Forfaitaire'), ('mixte', 'Mixte (Poids + Volume)')], help_text='Méthode de calcul du prix', max_length=20),
        ),
    ]
