# Generated by Django 5.2.4 on 2025-10-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessageattempt',
            name='region_override',
            field=models.CharField(blank=True, help_text='Région forcée (chine/mali)', max_length=20, null=True),
        ),
    ]
