# Generated by Django 5.2.4 on 2025-07-22 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_mali_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertargent',
            name='admin_chine',
            field=models.ForeignKey(blank=True, help_text='Administrateur Chine qui a confirmé la réception', limit_choices_to={'is_admin_chine': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_confirmes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertargent',
            name='admin_mali',
            field=models.ForeignKey(help_text='Administrateur Mali qui a initié le transfert', limit_choices_to={'is_admin_mali': True}, on_delete=django.db.models.deletion.CASCADE, related_name='transferts_inities', to=settings.AUTH_USER_MODEL),
        ),
    ]
