# Generated by Django 5.2.4 on 2025-09-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_changed_default_password',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a changé son mot de passe par défaut"),
        ),
    ]
