# Generated by Django 5.2.4 on 2025-07-26 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_in_app', models.BooleanField(default=True, verbose_name='Notifications in-app')),
                ('notifications_whatsapp', models.BooleanField(default=False, verbose_name='Notifications WhatsApp')),
                ('notifications_sms', models.BooleanField(default=False, verbose_name='Notifications SMS')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='client_app.client')),
            ],
            options={
                'verbose_name': 'Paramètres de notification',
                'verbose_name_plural': 'Paramètres de notification',
            },
        ),
    ]
