# Generated by Django 5.2.4 on 2025-07-22 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Description de la dépense', max_length=200)),
                ('type_depense', models.CharField(choices=[('transport', 'Transport'), ('manutention', 'Manutention'), ('douane', 'Frais de douane'), ('stockage', 'Stockage'), ('carburant', 'Carburant'), ('reparation', 'Réparation'), ('communication', 'Communication'), ('bureau', 'Frais de bureau'), ('autre', 'Autre')], help_text='Catégorie de la dépense', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant en FCFA', max_digits=10)),
                ('date_depense', models.DateField(default=django.utils.timezone.now, help_text='Date de la dépense')),
                ('justificatif', models.FileField(blank=True, help_text='Pièce justificative (facture, reçu, etc.)', null=True, upload_to='depenses/justificatifs/')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur la dépense')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planifiee', models.DateTimeField(help_text='Date et heure prévues pour la livraison')),
                ('date_livraison_effective', models.DateTimeField(blank=True, help_text='Date et heure effectives de livraison', null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('echec', 'Échec'), ('reprogrammee', 'Reprogrammée')], default='planifiee', max_length=20)),
                ('adresse_livraison', models.TextField(help_text='Adresse de livraison du colis')),
                ('telephone_destinataire', models.CharField(help_text='Téléphone du destinataire', max_length=15)),
                ('nom_destinataire', models.CharField(help_text='Nom de la personne qui a reçu le colis', max_length=200)),
                ('signature_destinataire', models.FileField(blank=True, help_text='Signature du destinataire', null=True, upload_to='livraisons/signatures/')),
                ('notes_livraison', models.TextField(blank=True, help_text='Notes sur la livraison')),
                ('montant_collecte', models.DecimalField(blank=True, decimal_places=2, help_text='Montant collecté lors de la livraison (si paiement au Mali)', max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_planifiee'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateTimeField(default=django.utils.timezone.now, help_text='Date et heure de réception du lot')),
                ('reception_complete', models.BooleanField(default=True, help_text='Le lot est-il reçu en totalité?')),
                ('observations', models.TextField(blank=True, help_text="Observations sur l'état du lot reçu")),
            ],
            options={
                'verbose_name': 'Réception de Lot',
                'verbose_name_plural': 'Réceptions de Lots',
                'ordering': ['-date_reception'],
            },
        ),
    ]
