# Generated by Django 5.2.4 on 2025-07-22 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_chine_app', '0002_initial'),
        ('agent_mali_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='agent',
            field=models.ForeignKey(help_text='Agent qui a effectué la dépense', limit_choices_to={'is_agent_mali': True}, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livraison',
            name='agent_livreur',
            field=models.ForeignKey(limit_choices_to={'is_agent_mali': True}, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livraison',
            name='colis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='agent_chine_app.colis'),
        ),
        migrations.AddField(
            model_name='receptionlot',
            name='agent_receptionnaire',
            field=models.ForeignKey(limit_choices_to={'is_agent_mali': True}, on_delete=django.db.models.deletion.CASCADE, related_name='lots_receptionnes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receptionlot',
            name='colis_endommages',
            field=models.ManyToManyField(blank=True, help_text='Colis endommagés lors de la réception', related_name='endommagements', to='agent_chine_app.colis'),
        ),
        migrations.AddField(
            model_name='receptionlot',
            name='colis_manquants',
            field=models.ManyToManyField(blank=True, help_text='Colis manquants lors de la réception', to='agent_chine_app.colis'),
        ),
        migrations.AddField(
            model_name='receptionlot',
            name='lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception_mali', to='agent_chine_app.lot'),
        ),
    ]
