# Generated by Django 5.2.4 on 2025-09-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_mali_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='statut_paiement',
            field=models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente de paiement')], default='en_attente', help_text='Statut du paiement du transport', max_length=20),
        ),
    ]
