# Generated by Django 5.2.4 on 2025-09-16 22:41

import ts_air_cargo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_mali_app', '0003_livraison_statut_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='justificatif',
            field=models.FileField(blank=True, help_text='Pièce justificative (facture, reçu, etc.) - Max 15MB', null=True, upload_to='depenses/justificatifs/', validators=[ts_air_cargo.validators.validate_justificatif_file, ts_air_cargo.validators.validate_filename_security]),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='signature_destinataire',
            field=models.FileField(blank=True, help_text='Signature du destinataire - Max 2MB, formats: JPG, PNG', null=True, upload_to='livraisons/signatures/', validators=[ts_air_cargo.validators.validate_signature_file, ts_air_cargo.validators.validate_filename_security]),
        ),
    ]
