# Generated by Django 5.2.4 on 2025-10-02 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0011_clientcreationtask'),
        ('agent_mali_app', '0004_alter_depense_justificatif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('jc', 'Jeton Cédé (JC)'), ('remise', 'Remise Commerciale'), ('frais_supplementaire', 'Frais Supplémentaire'), ('correction', 'Correction de Prix')], help_text="Type d'ajustement de prix", max_length=20)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, help_text="Montant de l'ajustement en FCFA (valeur absolue)", max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Prix original avant ajustement', max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Prix final après ajustement', max_digits=10)),
                ('reason', models.CharField(help_text="Raison de l'ajustement", max_length=200)),
                ('notes', models.TextField(blank=True, help_text="Notes additionnelles sur l'ajustement")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('applied', 'Appliqué'), ('cancelled', 'Annulé')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text="Date d'application de l'ajustement", null=True)),
                ('applied_by', models.ForeignKey(help_text="Agent Mali qui a appliqué l'ajustement", limit_choices_to={'is_agent_mali': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('colis', models.ForeignKey(help_text="Colis concerné par l'ajustement", on_delete=django.db.models.deletion.CASCADE, related_name='price_adjustments', to='agent_chine_app.colis')),
            ],
            options={
                'verbose_name': 'Ajustement de Prix',
                'verbose_name_plural': 'Ajustements de Prix',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['colis', 'status'], name='agent_mali__colis_i_573d68_idx'), models.Index(fields=['adjustment_type', 'created_at'], name='agent_mali__adjustm_9b75f3_idx'), models.Index(fields=['applied_by', 'created_at'], name='agent_mali__applied_d99462_idx')],
            },
        ),
    ]
