# Generated by Django 5.2.4 on 2025-10-06 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0011_clientcreationtask'),
        ('agent_mali_app', '0005_priceadjustment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receptionlot',
            options={'ordering': ['-date_derniere_maj'], 'verbose_name': 'Réception de lot', 'verbose_name_plural': 'Réceptions de lots'},
        ),
        migrations.RemoveField(
            model_name='receptionlot',
            name='colis_endommages',
        ),
        migrations.AddField(
            model_name='receptionlot',
            name='date_derniere_maj',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='receptionlot',
            name='nombre_colis_recus',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de colis reçus'),
        ),
        migrations.AlterField(
            model_name='receptionlot',
            name='colis_manquants',
            field=models.ManyToManyField(blank=True, related_name='receptions_manquantes', to='agent_chine_app.colis', verbose_name='Colis manquants'),
        ),
        migrations.AlterField(
            model_name='receptionlot',
            name='date_reception',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de première réception'),
        ),
        migrations.AlterField(
            model_name='receptionlot',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Historique des réceptions'),
        ),
        migrations.AlterField(
            model_name='receptionlot',
            name='reception_complete',
            field=models.BooleanField(default=False, verbose_name='Réception complète'),
        ),
    ]
