# Generated by Django 5.2.4 on 2025-10-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_mali_app', '0006_alter_receptionlot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionlot',
            name='frais_dedouanement',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de dédouanement pour le lot (en FCFA)', max_digits=10, verbose_name='Frais de dédouanement (FCFA)'),
        ),
    ]
