# Generated by Django 5.2.4 on 2025-10-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_mali_app', '0007_receptionlot_frais_dedouanement 2'),
        ('agent_mali_app', '0007_receptionlot_frais_dedouanement'),
    ]

    operations = [
    ]
