# Generated by Django 5.2.4 on 2025-07-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField(help_text='Adresse complète du client')),
                ('pays', models.CharField(choices=[('ML', 'Mali'), ('SN', 'Sénégal'), ('CI', "Côte d'Ivoire"), ('BF', 'Burkina Faso'), ('NE', 'Niger'), ('GN', 'Guinée'), ('MR', 'Mauritanie'), ('GM', 'Gambie'), ('GW', 'Guinée-Bissau')], default='ML', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_suivi', models.CharField(editable=False, help_text='Numéro de suivi auto-généré: TS...', max_length=20, unique=True)),
                ('longueur', models.DecimalField(decimal_places=2, help_text='Longueur en cm', max_digits=6)),
                ('largeur', models.DecimalField(decimal_places=2, help_text='Largeur en cm', max_digits=6)),
                ('hauteur', models.DecimalField(decimal_places=2, help_text='Hauteur en cm', max_digits=6)),
                ('poids', models.DecimalField(decimal_places=2, help_text='Poids en kg', max_digits=8)),
                ('prix_calcule', models.DecimalField(decimal_places=2, editable=False, help_text='Prix calculé automatiquement', max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('paye_chine', 'Payé en Chine'), ('paye_mali', 'Payé au Mali'), ('non_paye', 'Non Payé')], default='non_paye', max_length=20)),
                ('statut', models.CharField(choices=[('receptionne_chine', 'Réceptionné en Chine'), ('en_transit', 'En Transit'), ('arrive_mali', 'Arrivé au Mali'), ('livre', 'Livré'), ('perdu', 'Perdu')], default='receptionne_chine', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description du contenu du colis')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(editable=False, help_text='Numéro auto-généré: date + chiffres', max_length=20, unique=True)),
                ('prix_transport', models.DecimalField(blank=True, decimal_places=2, help_text='Prix total du transport du lot', max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('expedie', 'Expédié'), ('en_transit', 'En Transit'), ('arrive', 'Arrivé au Mali'), ('livre', 'Livré')], default='ouvert', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('date_expedition', models.DateTimeField(blank=True, null=True)),
                ('date_arrivee', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['-date_creation'],
            },
        ),
    ]
