# Generated by Django 5.2.4 on 2025-07-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo du colis', null=True, upload_to='colis_images/'),
        ),
        migrations.AddField(
            model_name='colis',
            name='type_transport',
            field=models.CharField(choices=[('cargo', 'Cargo'), ('express', 'Express'), ('bateau', 'Bateau')], default='cargo', help_text='Type de transport: Cargo/Express (par poids) ou Bateau (par dimensions)', max_length=20),
        ),
    ]
