# Generated by Django 5.2.4 on 2025-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0003_colis_image_colis_type_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En Attente'), ('receptionne_chine', 'Réceptionné en Chine'), ('en_transit', 'En Transit'), ('arrive', 'Arrivé au Mali'), ('livre', 'Livré'), ('perdu', 'Perdu')], default='receptionne_chine', max_length=20),
        ),
    ]
