# Generated by Django 5.2.4 on 2025-09-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0004_alter_colis_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='frais_douane',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Frais de douane saisis par l'agent Mali", max_digits=10, null=True),
        ),
    ]
