# Generated by Django 5.2.4 on 2025-09-16 22:41

import ts_air_cargo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0005_lot_frais_douane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo du colis (max 5MB, formats: JPG, PNG, GIF, WebP)', null=True, upload_to='colis_images/', validators=[ts_air_cargo.validators.validate_colis_image, ts_air_cargo.validators.validate_filename_security]),
        ),
    ]
