# Generated by Django 5.2.4 on 2025-09-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0006_alter_colis_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='type_lot',
            field=models.CharField(choices=[('cargo', 'Cargo'), ('express', 'Express'), ('bateau', 'Bateau')], default='cargo', help_text='Type de transport principal du lot', max_length=20),
        ),
        migrations.AlterField(
            model_name='lot',
            name='numero_lot',
            field=models.CharField(editable=False, help_text='Numéro auto-généré: TYPE-YYYYMMDDXXX', max_length=30, unique=True),
        ),
    ]
