# Generated by Django 5.2.4 on 2025-09-25 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0007_add_type_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColisCreationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Identifiant unique de la tâche', max_length=50, unique=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='ID de la tâche Celery', max_length=100, null=True)),
                ('operation_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification')], help_text="Type d'opération (création ou modification)", max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('image_uploading', 'Upload image...'), ('price_calculating', 'Calcul prix...'), ('notification_sending', 'Envoi notification...'), ('completed', 'Finalisé'), ('failed', 'Échec'), ('failed_retry', 'Échec - retry programmé'), ('failed_final', 'Échec définitif'), ('cancelled', 'Annulé')], default='pending', help_text='État actuel de la tâche', max_length=20)),
                ('current_step', models.CharField(blank=True, help_text='Étape en cours de traitement', max_length=100)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Pourcentage de progression (0-100)')),
                ('colis_data', models.JSONField(help_text='Données du formulaire colis sérialisées en JSON')),
                ('original_image_path', models.CharField(blank=True, help_text="Chemin vers l'image temporaire", max_length=500)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur en cas d'échec")),
                ('retry_count', models.IntegerField(default=0, help_text='Nombre de tentatives effectuées')),
                ('max_retries', models.IntegerField(default=3, help_text='Nombre maximum de tentatives')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='Date de la prochaine tentative', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la tâche')),
                ('started_at', models.DateTimeField(blank=True, help_text='Date de début de traitement', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date de fin de traitement', null=True)),
                ('colis', models.ForeignKey(blank=True, help_text='Colis créé (null pendant le traitement)', null=True, on_delete=django.db.models.deletion.CASCADE, to='agent_chine_app.colis')),
                ('initiated_by', models.ForeignKey(help_text='Agent qui a initié la tâche', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(help_text='Lot de destination', on_delete=django.db.models.deletion.CASCADE, to='agent_chine_app.lot')),
            ],
            options={
                'verbose_name': 'Tâche de Colis',
                'verbose_name_plural': 'Tâches de Colis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='agent_chine_status_fbd880_idx'), models.Index(fields=['initiated_by', 'status'], name='agent_chine_initiat_43e843_idx'), models.Index(fields=['lot', 'status'], name='agent_chine_lot_id_eb8756_idx')],
            },
        ),
    ]
