# Generated by Django 5.2.4 on 2025-09-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0008_coliscreationtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coliscreationtask',
            name='original_image_path',
            field=models.CharField(blank=True, help_text="Chemin vers l'image temporaire", max_length=500, null=True),
        ),
    ]
