# Generated by Django 5.2.4 on 2025-09-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0009_alter_coliscreationtask_original_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='prix_transport_manuel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix de transport manuel défini par l'agent (prioritaire sur le calcul automatique)", max_digits=10, null=True),
        ),
    ]
