# Generated by Django 5.2.4 on 2025-10-02 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0010_colis_prix_transport_manuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCreationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Identifiant unique de la tâche', max_length=50, unique=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='ID de la tâche Celery', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('account_creating', 'Création compte...'), ('notification_sending', 'Envoi notifications...'), ('completed', 'Terminé'), ('failed', 'Échec'), ('failed_retry', 'Échec - retry programmé'), ('failed_final', 'Échec définitif')], default='pending', help_text='État actuel de la tâche', max_length=20)),
                ('current_step', models.CharField(blank=True, help_text='Étape en cours de traitement', max_length=100)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Pourcentage de progression (0-100)')),
                ('telephone', models.CharField(help_text='Numéro de téléphone du client', max_length=20)),
                ('first_name', models.CharField(help_text='Prénom du client', max_length=100)),
                ('last_name', models.CharField(help_text='Nom du client', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email du client', max_length=254)),
                ('notifications_data', models.JSONField(blank=True, help_text='Données des notifications envoyées', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur en cas d'échec")),
                ('retry_count', models.IntegerField(default=0, help_text='Nombre de tentatives effectuées')),
                ('max_retries', models.IntegerField(default=3, help_text='Nombre maximum de tentatives')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='Date de la prochaine tentative', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la tâche')),
                ('started_at', models.DateTimeField(blank=True, help_text='Date de début de traitement', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date de fin de traitement', null=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client créé (null pendant le traitement)', null=True, on_delete=django.db.models.deletion.CASCADE, to='agent_chine_app.client')),
                ('initiated_by', models.ForeignKey(help_text='Agent qui a initié la tâche', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche de Création Client',
                'verbose_name_plural': 'Tâches de Création Client',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='agent_chine_status_b6b895_idx'), models.Index(fields=['initiated_by', 'status'], name='agent_chine_initiat_f9713f_idx'), models.Index(fields=['telephone', 'status'], name='agent_chine_telepho_2b9f95_idx')],
            },
        ),
    ]
