# Generated by Django 5.2.4 on 2025-10-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0011_clientcreationtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['-date_creation'], 'verbose_name_plural': 'Lots'},
        ),
        migrations.AddField(
            model_name='lot',
            name='benefice',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Bénéfice calculé (prix transport + frais douane - total colis)', max_digits=12, null=True),
        ),
    ]
