# Generated by Django 5.2.4 on 2025-11-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_chine_app', '0012_alter_lot_options_lot_benefice'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='quantite_pieces',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de pièces (pour téléphones/électronique)'),
        ),
        migrations.AddField(
            model_name='colis',
            name='type_colis',
            field=models.CharField(choices=[('standard', 'Standard (au kilo)'), ('telephone', 'Téléphone (à la pièce)'), ('electronique', 'Électronique (à la pièce)')], default='standard', help_text='Type de tarification : Standard (au kilo) ou à la pièce', max_length=20),
        ),
    ]
